http.host: 0.0.0.0

# Uncomment the following lines for a production cluster deployment
# #transport.host: 0.0.0.0
# #discovery.zen.minimum_master_nodes: 1

### x-pack functions

xpack.security.enabled: false
xpack.monitoring.enabled: true
xpack.graph.enabled: false
xpack.watcher.enabled: false


http.cors.allow-origin: "*"
http.cors.enabled: true

### 起動時のメモリ固定化
#bootstrap.mlockall: true
