version: '2'
services:
  elasticsearch:
    build: elasticsearch
    #mem_limit: 512MB
    volumes:
        - es-data:/usr/share/elasticsearch/data
        - ./elasticsearch/config:/usr/share/elasticsearch/config
    ports:
        - "9200:9200"
    expose:
        - "9300"
    container_name: elasticsearch
    hostname: elasticsearch
    ulimits:
        nofile:
            soft: 65536
            hard: 65536
        # https://github.com/docker-library/elasticsearch/issues/111
        # uliimit
    environment:
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      #ES_HEAP_SIZE: 512m
  kibana:
    build: kibana
    environment:
        - ELASTICSEARCH_URL=http://elasticsearch:9200
    links:
        - elasticsearch:elasticsearch
    ports:
        - 80:5601

volumes:
    es-data:
        driver: local

